image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 5100
    onOpen: open-browser
    visibility: public
  - port: 6379
    onOpen: ignore
  - port: 27017
    onOpen: ignore
  - port: 3100 # Creator
    onOpen: open-browser
    visibility: public
# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: sh ./.scripts/gitpod_setup.sh
  - name: Mongo
    init: |
      mkdir -p /workspace/mongodb/data/db
    command: |
      mongod --replSet rs0 --dbpath /workspace/mongodb/data/db
  - command: |
      gp await-port 27017
      mongo steedos --eval "rs.initiate()"
      exit
  - name: Redis
    command: |
      redis-server --save "" --appendonly no --client-output-buffer-limit replica 0 0 0 --client-output-buffer-limit pubsub 0 0 0 --client-output-buffer-limit slave 0 0 0
  - name: Steedos
    init: |
      yarn
      yarn bootstrap
      yarn build
    command: |
      sh ./.scripts/gitpod_env.sh
      gp await-port 27017
      gp await-port 6379
      export ROOT_URL=$(gp url 5100)
      yarn start
vscode:
  extensions:
    - dbaeumer.vscode-eslint
