# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish Latest Steedos Platform

on:
  push:
     branches:
       - publish-latest
  # push:
  #   tags:
  #     - 'v**'
jobs:
  release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      # - name: Checkout branche
      #   run: |
      #     git checkout next
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - uses: meteorengineer/setup-meteor@v1
        with:
          meteor-release: '1.9.3'
      - run: yarn --frozen-lockfile
      - name: Bootstrap platform
        run: |
          yarn bootstrap
      - name: Build platform
        env:
          CI: false
        run: |
          npx browserslist@latest --update-db
          npm install -g mkdirp
          yarn build
      - name: Build creator
        run: |
          yarn build_creator
      - name: Push creator build
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add . 
          git commit -m 'creator build'
          git push
      - name: Lerna version
        run: |
          lerna version patch --no-git-tag-version --force-publish --exact --yes
      - name: Set current version
        run: |
          CURRENT_VERSION=$(node -p 'require("./lerna.json").version')
          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
      - name: Create commits & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add . 
          git commit -m v${{ env.CURRENT_VERSION }}
          git push
      - name: Upgrade template
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          yarn upgrade-template
      - name: Lerna publish
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          lerna publish from-package --yes
        env:
          CI: false
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Create tag
        run: |
          git tag -a v${{ env.CURRENT_VERSION }} -m 'published v${{ env.CURRENT_VERSION }}' 
          git push origin --tags
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v${{ env.CURRENT_VERSION }}
          release_name: v${{ env.CURRENT_VERSION }}
          draft: false
          prerelease: false
      - name: Sync to taobao registry
        run: |
          npm install cnpm -g
          open https://npm.taobao.org/sync/@steedos/app-admin
          open https://npm.taobao.org/sync/@steedos/app-contracts
          open https://npm.taobao.org/sync/@steedos/app-crm
          open https://npm.taobao.org/sync/@steedos/app-oa
          open https://npm.taobao.org/sync/@steedos/app-okr-management
          open https://npm.taobao.org/sync/@steedos/app-project-management
          open https://npm.taobao.org/sync/@steedos/accounts
          open https://npm.taobao.org/sync/@steedos/auth
          open https://npm.taobao.org/sync/@steedos/client
          open https://npm.taobao.org/sync/@steedos/core
          open https://npm.taobao.org/sync/create-steedos-app
          open https://npm.taobao.org/sync/@steedos/design-system-react
          open https://npm.taobao.org/sync/@steedos/filters
          open https://npm.taobao.org/sync/@steedos/formula
          open https://npm.taobao.org/sync/@steedos/i18n
          open https://npm.taobao.org/sync/@steedos/meteor-bundle-dependencies
          open https://npm.taobao.org/sync/@steedos/meteor-bundle-runner
          open https://npm.taobao.org/sync/@steedos/migrate
          open https://npm.taobao.org/sync/@steedos/objectql
          open https://npm.taobao.org/sync/@steedos/plugin-enterprise
          open https://npm.taobao.org/sync/@steedos/process
          open https://npm.taobao.org/sync/@steedos/steedos-project-template
          open https://npm.taobao.org/sync/@steedos/react
          open https://npm.taobao.org/sync/@steedos/schemas
          open https://npm.taobao.org/sync/@steedos/standard-objects
          open https://npm.taobao.org/sync/@steedos/plugin-dingtalk
          open https://npm.taobao.org/sync/@steedos/plugin-qywx
          open https://npm.taobao.org/sync/@steedos/steedos-plugin-schema-builder
          open https://npm.taobao.org/sync/@steedos/tailwind
          open https://npm.taobao.org/sync/@steedos/webapp
          open https://npm.taobao.org/sync/@steedos/workflow
          open https://npm.taobao.org/sync/steedos-server
          open https://npm.taobao.org/sync/@steedos/service-api
          open https://npm.taobao.org/sync/@steedos/service-metadata-apps
          open https://npm.taobao.org/sync/@steedos/service-metadata-objects
          open https://npm.taobao.org/sync/@steedos/service-metadata-permissionsets
          open https://npm.taobao.org/sync/@steedos/service-metadata-server
          open https://npm.taobao.org/sync/@steedos/service-metadata-translations
          open https://npm.taobao.org/sync/@steedos/service-metadata-triggers
          open https://npm.taobao.org/sync/@steedos/service-metadata
          open https://npm.taobao.org/sync/@steedos/service-meteor-package-loader
          open https://npm.taobao.org/sync/@steedos/service-mongodb-server
          open https://npm.taobao.org/sync/@steedos/service-node-red
          open https://npm.taobao.org/sync/@steedos/service-package-loader
          open https://npm.taobao.org/sync/@steedos/service-steedos-server
          open https://npm.taobao.org/sync/@steedos/service-charts
          open https://npm.taobao.org/sync/@steedos/service-package-registry
          open https://npm.taobao.org/sync/@steedos/service-packages
          open https://npm.taobao.org/sync/@steedos/service-pages
          open https://npm.taobao.org/sync/@steedos/service-metadata-tabs
          open https://npm.taobao.org/sync/@steedos/service-fields-indexs
          open https://npm.taobao.org/sync/@steedos/service-cloud-init
          open https://npm.taobao.org/sync/@steedos/metadata-api
          open https://npm.taobao.org/sync/@steedos/service-accounts
